# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Unshallow git
      run: git fetch --unshallow
    - name: Build with Maven
      run: >-
        mvn -B package test verify
        -Dgpg.skip=true
        -Dmaven.javadoc.skip=true
        -Dmaven.source.skip=true
        -Pcoverage,sonar
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=hdsdi3g
        -Dsonar.projectKey=hdsdi3g_prodlib
        -Dsonar.java.coveragePlugin=jacoco
        -Dsonar.dynamicAnalysis=reuseReports
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco-aggregate/jacoco.xml
        --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
